### ISSUE TITLE
sentencepiece

### ISSUE THREAD

**Issue by paulVu** [realminchoi/babyagi-ui#1]
`[end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece`

Run on MacBook m1, I was xcode-select --install, Python 3.11

**Comment by realminchoi** [comment]
sentencepiece doesn't support Python 3.11, there is an open issue about this [Support for python3.11 #810](https://github.com/google/sentencepiece/issues/810)

Try to run it on Python 3.10

**Comment by xdite** [comment]
also you can try `brew install  sentencepiece`

**Comment by paulVu** [comment]
thanks
