### ISSUE TITLE
zsh: illegal hardware instruction python -m streamlit run babyagi.py

### ISSUE THREAD

**Issue by alexechoi** [realminchoi/babyagi-ui#3]
I keep encountering this issue of ``` [python -m streamlit run babyagi.py](zsh: illegal hardware instruction python -m streamlit run babyagi.py)``` whenever I try to run this. Anyone have any tips of how to fix this?

**Comment by realminchoi** [comment]
What hardware are you using?

**Comment by alexechoi** [comment]
MacBook Pro M1 Chip

**Comment by realminchoi** [comment]
Make sure you are running Python 3.10 and not Python 3.11, there may be packages not supported in 3.11 yet for MacBook M1

**Comment by alexechoi** [comment]
Thanks, I was originally on Python 3.9 and I created an additional conda environment with Python 3.8 and now it works very well!
